import fs from 'node:fs';
import path from 'node:path';
import { run } from './exec';
import type { RunDirs } from './runWorkspace';
import type { WorkerConfig } from './config';
import type { TaskTrigger } from '../../shared/src/types';

/**
 * M5: run the agent-based SDD pipeline (`pipeline/pipeline.sh`) as a fresh
 * process, with the flattened TaskTrigger fields and run paths exported as
 * environment variables (the contract in `sdd-pipeline` spec §"Working
 * directory and environment per stage").
 *
 * Returns the pipeline's exit code: 0 = completed (the verdict is read
 * separately from the verification artifact), non-zero = a stage hard-failed.
 */
export async function runPipeline(
  dirs: RunDirs,
  trigger: TaskTrigger,
  config: WorkerConfig,
): Promise<number> {
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    ANTHROPIC_API_KEY: config.anthropicApiKey,
    RUN_DIR: dirs.root,
    MAX_STAGE_RETRIES: String(config.maxStageRetries),
    MAX_VERIFY_RETRIES: String(config.maxVerifyRetries),
    ENABLE_PLAN_CHALLENGE: String(config.enablePlanChallenge),
    // Flattened TaskTrigger — consumed by pipeline.sh / the agents.
    TRIGGER_ID: trigger.triggerId,
    TRIGGER_SOURCE: trigger.source,
    ACTOR: trigger.actor,
    ISSUE_NUMBER: String(trigger.issue.number),
    ISSUE_TITLE: trigger.issue.title,
    ISSUE_BODY: trigger.issue.body,
    ISSUE_URL: trigger.issue.url,
    ISSUE_AUTHOR: trigger.issue.author,
    REPO_OWNER: trigger.repo.owner,
    REPO_NAME: trigger.repo.name,
  };

  const { code } = await run('bash', [config.pipelineScript], {
    cwd: dirs.repo,
    env,
    logFile: path.join(dirs.logs, 'pipeline.log'),
  });
  return code;
}

export type Verdict = 'PASS' | 'FAIL';

export interface PipelineOutcome {
  verdict: Verdict;
  /** Markdown PR body assembled from the agent artifacts. */
  prBody: string;
}

/** Newest file in `dir` whose name ends with `suffix`, or null. */
function latestArtifact(dir: string, suffix: string): string | null {
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    return null;
  }
  const matches = entries
    .filter(name => name.endsWith(suffix))
    .map(name => path.join(dir, name))
    .map(file => ({ file, mtime: fs.statSync(file).mtimeMs }))
    .sort((a, b) => b.mtime - a.mtime);
  return matches[0]?.file ?? null;
}

function readArtifact(dir: string, suffix: string): string | null {
  const file = latestArtifact(dir, suffix);
  if (!file) return null;
  try {
    return fs.readFileSync(file, 'utf-8');
  } catch {
    return null;
  }
}

/**
 * Read the agent artifacts (via the `artifacts/` → `.claude/sdd-tracking`
 * symlink) and compose the verdict + PR body.
 *
 * Verdict comes from the first line of the latest verification report
 * (`VERDICT: PASS|FAIL`); anything else (missing/unparseable) is treated as
 * FAIL so a questionable run lands as a draft rather than a confident PR.
 */
export function readPipelineOutcome(dirs: RunDirs, trigger: TaskTrigger): PipelineOutcome {
  const artifacts = dirs.artifacts; // symlink to repo/.claude/sdd-tracking
  const plan = readArtifact(path.join(artifacts, 'plans'), '-plan.instructions.md');
  const changes = readArtifact(path.join(artifacts, 'changes'), '-changes.md');
  const verification = readArtifact(path.join(artifacts, 'verification'), '-verification.md');

  const verdict: Verdict =
    verification && /^VERDICT:\s*PASS\b/m.test(verification.split('\n')[0]) ? 'PASS' : 'FAIL';

  const prBody = composePrBody(trigger, verdict, { plan, changes, verification });
  return { verdict, prBody };
}

function section(title: string, content: string | null): string {
  if (!content) return `## ${title}\n\n_(not produced)_`;
  return `## ${title}\n\n${content.trim()}`;
}

function composePrBody(
  trigger: TaskTrigger,
  verdict: Verdict,
  parts: { plan: string | null; changes: string | null; verification: string | null },
): string {
  const header = [
    `Generated by the remote SDD agent for issue #${trigger.issue.number}.`,
    '',
    verdict === 'PASS'
      ? '✅ **Verification: PASS**'
      : '⚠️ **Verification: FAIL** — opened as a draft; see the verification report below.',
    '',
    `Closes #${trigger.issue.number}.`,
  ].join('\n');

  const verificationBlock = parts.verification
    ? `<details>\n<summary>Verification report</summary>\n\n${parts.verification.trim()}\n\n</details>`
    : '## Verification\n\n_(not produced)_';

  return [
    header,
    section('Plan', parts.plan),
    section('Changes', parts.changes),
    verificationBlock,
  ].join('\n\n');
}
